name: Run Automation Scripts

on:
  workflow_dispatch:
    inputs:
      script_name:
        description: 'The name of the script to execute'
        required: true

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn sqlalchemy psycopg2 requests

      - name: Run script
        run: |
          start_time=$(date +%s)
          python scripts/${{ github.event.inputs.script_name }}
          status=$?
          end_time=$(date +%s)
          duration=$(( (end_time - start_time) / 60 ))
          result_status="success"
          if [ $status -ne 0 ]; then
            result_status="failed"
          fi
          curl -X POST ${{ secrets.API_URL }} -H "Content-Type: application/json" -d '{
            "script_name": "${{ github.event.inputs.script_name }}",
            "trigger_time": "'$(date --iso-8601=seconds)'",
            "duration_minutes": '$duration',
            "result_status": "'$result_status'"
          }'
